# This is a basic workflow to help you get started with Actions
name: Android CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build debug apk
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.12.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v4
    
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build debug apk
        uses: gradle/gradle-build-action@v3
        with:
          arguments: assembleDebug
          distributions-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true

      - name: Upload debug apk
        uses: actions/upload-artifact@v4
        with:
          name: apk-debug
          path: app/build/outputs/apk/debug
